server:
  port: 9999
  forward-headers-strategy: true
  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
  servlet:
    session:
      timeout: 86400

spring:
  transaction:
    rollback-on-commit-failure: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/home_rent?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  mvc:
    view:
      #注意路径与存放jsp文件的目录一致
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
  mapper-locations:
    - classpath*:mappers/*Mapper.xml
  type-aliases-package: com.mappers
application:
  version: 1.1.0
  staticCdnUrl:
